// <auto-generated />
using System;
using Fisioterapia.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Fisioterapia.Models.Migrations.SqlServerMigrations
{
    [DbContext(typeof(SqlServerContext))]
    [Migration("20201101155430_MigAtualizarDb")]
    partial class MigAtualizarDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Atleta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Altura")
                        .HasColumnType("real");

                    b.Property<string>("Celular")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Idade")
                        .HasColumnType("datetime2");

                    b.Property<string>("LadoDominante")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<byte>("OcorreuContusao")
                        .HasColumnType("tinyint");

                    b.Property<float>("Peso")
                        .HasColumnType("real");

                    b.Property<string>("Posicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Profissao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Atletas");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Auxiliar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Expiracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Instituicao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Periodo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auxiliars");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.AuxiliarUsuarios", b =>
                {
                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<int>("IdAuxiliar")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario", "IdAuxiliar");

                    b.HasIndex("IdAuxiliar");

                    b.ToTable("AuxiliarUsuarios");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.ExameExercicios", b =>
                {
                    b.Property<int>("IdExame")
                        .HasColumnType("int");

                    b.Property<int>("IdExercios")
                        .HasColumnType("int");

                    b.HasKey("IdExame", "IdExercios");

                    b.HasIndex("IdExercios");

                    b.ToTable("ExameExercicios");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Exames", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAtleta")
                        .HasColumnType("int");

                    b.Property<int>("IdAuxiliar")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdAtleta");

                    b.HasIndex("IdAuxiliar");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Exames");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Exercicios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Exercicios");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Logs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdUsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("Index")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuarioId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Usuarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("AceitoTermos")
                        .HasColumnType("bit");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Atualizado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Criado")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SenhaReset")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificacaoToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Verificado")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Auxiliar", b =>
                {
                    b.HasOne("Fisioterapia.Models.Entidades.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.AuxiliarUsuarios", b =>
                {
                    b.HasOne("Fisioterapia.Models.Entidades.Auxiliar", "Auxiliar")
                        .WithMany("AuxiliarUsuarios")
                        .HasForeignKey("IdAuxiliar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fisioterapia.Models.Entidades.Usuarios", "Usuarios")
                        .WithMany("AuxiliarUsuarios")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.ExameExercicios", b =>
                {
                    b.HasOne("Fisioterapia.Models.Entidades.Exames", "Exames")
                        .WithMany("ExameExercicios")
                        .HasForeignKey("IdExame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fisioterapia.Models.Entidades.Exercicios", "Exercicios")
                        .WithMany("ExameExercicios")
                        .HasForeignKey("IdExercios")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Exames", b =>
                {
                    b.HasOne("Fisioterapia.Models.Entidades.Atleta", "Atleta")
                        .WithMany()
                        .HasForeignKey("IdAtleta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fisioterapia.Models.Entidades.Auxiliar", "Auxiliar")
                        .WithMany()
                        .HasForeignKey("IdAuxiliar")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Fisioterapia.Models.Entidades.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Exercicios", b =>
                {
                    b.HasOne("Fisioterapia.Models.Entidades.Usuarios", "Usuarios")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Logs", b =>
                {
                    b.HasOne("Fisioterapia.Models.Entidades.Usuarios", "IdUsuario")
                        .WithMany()
                        .HasForeignKey("IdUsuarioId");
                });

            modelBuilder.Entity("Fisioterapia.Models.Entidades.Usuarios", b =>
                {
                    b.OwnsMany("Fisioterapia.Models.Entidades.RefreshToken", "RecarregarToken", b1 =>
                        {
                            b1.Property<int>("UsuariosId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime>("Created")
                                .HasColumnType("datetime2");

                            b1.Property<string>("CreatedById")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("Expires")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ReplacedByToken")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime?>("Revoked")
                                .HasColumnType("datetime2");

                            b1.Property<string>("RevokedById")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Token")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("UsuariosId", "Id");

                            b1.ToTable("RefreshToken");

                            b1.WithOwner("Usuarios")
                                .HasForeignKey("UsuariosId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
